#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
sudo apt update -y
sudo apt install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx start
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
