#!/usr/bin/env bash
#number -eq multiple of 3 & 5 display 'FizzBuzz'
#number -eq multiple of 3 display 'Fizz'
#number -eq multiple of 5 display 'Buzz'
#otherwise display number in list format

number=0

while [ $number -le 100 ]
do
	if (( number % 3 == 0 && number % 5 == 0))
	then
		echo "FizzBuzz"
	elif (( number%3==0 ))
	then
		echo "Fizz"
	elif (( number%5==0 ))
	then
		echo "Buzz"
	else
		echo $number
	fi
(( number++ ))
done
