#!/usr/bin/env bash
# The beautiful story using the content of passwd
#f1=username f2=password f3=userid f4=groupid f5=userinfo f6=homedir f7=shellpath

while IFS=':' read -r f1 f2 f3 f4 f5 f6 f7
do
echo "The user $f1 is part of the $f4 gang,"\
	"lives in $f6 and rides $f7."\
	"$f3's place is protected by the passcode $f2,"\
	"more info about the user here: $f5"
done < "/etc/passwd"
