#!/usr/bin/env bash
#combining while loop, with if, elif and else conditions
# display 'bad luck' for 4th iteration
# display 'good luck' for 8th iteration
# for others display 'Best School'

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
(( counter++ ))
done
