#!/usr/bin/env bash
#display 1-20 using while loop with case statement
# display '4' and 'bad luck from China' for 4th iteration
# display '9' and 'bad luck from Japan' for 9th iteration
# display '17' and 'bad luck from Italy' for 17th iteration
# for others display 'Best School'

counter=1

while [ $counter -le 20 ]
do
	echo $counter
	case $counter in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
(( counter++ ))
done
