#!/usr/bin/env bash

# Create the nginx user if it doesn't exist
if ! id -u nginx >/dev/null 2>&1; then
    useradd -r -s /usr/sbin/nologin nginx
fi

# Configure Nginx to run as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Configure Nginx to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2

# Start Nginx
sudo -u nginx service nginx start

