#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Stop Nginx if it is already running
service nginx stop

# Configure Nginx to run as the nginx user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Configure Nginx to listen on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Start Nginx
service nginx start

